### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by Se1d228** [guighub/MIDI2GD#1]
![image](https://github.com/guighub/MIDI2GD/assets/114381573/9cbaff08-6332-41dd-9427-9a81e2876450)

**Comment by guighub** [comment]
Hmm, this seems like it might be a problem with the GeometryDashAPI library not being up to date with the latest version of GD's level format. I'll try to see if I can replicate this later and update the library to the latest release if so.

**Comment by guighub** [comment]
Alright I've updated the GeometryDashAPI library in the most recent release, hopefully that fixes the error?

**Comment by Se1d228** [comment]
> Alright I've updated the GeometryDashAPI library in the most recent release, hopefully that fixes the error?

Still no :(
![image](https://github.com/guighub/MIDI2GD/assets/114381573/602893ff-69f6-4e07-ac3e-81434cc63444)

**Comment by Se1d228** [comment]
Not that photo

**Comment by Se1d228** [comment]
![Снимок экрана 2024-04-11 171525](https://github.com/guighub/MIDI2GD/assets/114381573/cd209fc4-36bc-4df3-9d9b-e58d840c66af)

**Comment by guighub** [comment]
This should now be fixed in [v1.0.4](https://github.com/guighub/MIDI2GD/releases/tag/v1.0.4)
If it still doesn't work feel free to reopen the issue!
