### ISSUE TITLE
Your name and year in the licence

### ISSUE THREAD

**Issue by Folleach** [guighub/MIDI2GD#3]
There are blank fields in the [LICENCE.txt](https://github.com/guighub/MIDI2GD/blob/64818491128f536ba60f32d8d17aa4278d81fd08/LICENSE.txt), you can fill them in, heh

https://github.com/guighub/MIDI2GD/blob/64818491128f536ba60f32d8d17aa4278d81fd08/LICENSE.txt#L1-L4

**Comment by guighub** [comment]
Oops, thank you for letting me know. I'll fix that now.
